name: Build firmware

on:
    push:
      branches: ['main']
      paths: ['src/**']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: generate mock secrets header
        run: cp include/secrets.h.example include/secrets.h

      - name: Generate littlefs image
        run: pio run -e antcontroller -t buildfs
    
      - name: Build the project and generate whole binary image
        run: pio run -e antcontroller -t mergebin

      - name: Export compiled binary
        uses: actions/upload-artifact@v3
        with:
          name: firmware.bin
          path: merged-flash.bin