name: Build firmware

on:
    push:
      branches: ['main']
      paths: ['src/**', 'platformio.ini']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

    #   - name: generate mock secrets header
    #     run: cp include/secrets.h.example include/secrets.h

      - name: Fetch frontend
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: pio run -e antcontroller -t fetchfrontend
        
      - name: Generate littlefs image
        run: pio run -e antcontroller -t buildfs
    
      - name: Prepare firmware binaries
        run: pio run -e antcontroller -t fwimage

      - name: Build the project and generate full image
        run: pio run -e antcontroller -t fullimage

      - name: Export full binary image
        uses: actions/upload-artifact@v3
        with:
          name: fullimage.bin
          path: bin/fullimage.bin

      - name: Export firmware binary
        uses: actions/upload-artifact@v3
        with:
          name: firmware.bin
          path: bin/firmware.bin